services:
   voxl:
    image: voxl-smip:runtime-arm64
    container_name: smip-voxl-runtime
    hostname: smip-voxl-runtime
    privileged: true
    network_mode: host
    ipc: host
    cpuset: "4-6"
    ulimits:
      rtprio: 40
    volumes:
      - ./smip_uav_ws:/smip_uav_ws
      - ./data_log:/data_log
      - ./entrypoint.sh:/entrypoint.sh
      - /dev:/dev
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: ["bash"]
    entrypoint: ["/entrypoint.sh"]
