services:

  dev-amd64:
    build:
      context: .
      dockerfile: Dockerfile
      target: smip-dev
    image: voxl-smip:dev-amd64
    container_name: smip-dev-amd64
    privileged: true
    network_mode: host
    volumes:
      - ../smip_uav:/smip_uav_ws/src/smip_uav
      - ../build:/smip_uav_ws/build
      - ../install:/smip_uav_ws/install
      - ../log:/smip_uav_ws/log
      - /dev:/dev
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    stdin_open: true
    tty: true
    entrypoint: ["/entrypoint.sh"]
    command: ["bash"]

  dev-arm64:
    build:
      dockerfile: Dockerfile
      context: .
      target: smip-dev
    image: voxl-smip:dev-arm64
    container_name: smip-dev-arm64
    privileged: true
    network_mode: host
    volumes:
      - ../smip_uav:/smip_uav_ws/src/smip_uav
      - smip-cross-build:/smip_uav_ws/build
      - smip-cross-install:/smip_uav_ws/install
      - smip-cross-log:/smip_uav_ws/log
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    stdin_open: true
    tty: true
    command: /bin/bash

  extract:
    image: voxl-smip:dev-arm64
    container_name: smip-extract
    volumes:
      - smip-cross-install:/install_from:ro
      - ./deploy/smip_uav_ws/install:/install_to
    command: bash -c "cp -aL /install_from/. /install_to/"

volumes:
  smip-cross-build:
    name: smip-cross-build
  smip-cross-install:
    name: smip-cross-install
  smip-cross-log:
    name: smip-cross-log